# Generated by Django 2.1.5 on 2019-02-11 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lna', '0002_auto_20190211_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exposure',
            name='file_path',
            field=models.FilePathField(default=None, verbose_name='File Path'),
        ),
    ]
