# Generated by Django 2.1.5 on 2019-02-11 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lna', '0003_auto_20190211_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exposure',
            name='file_type',
            field=models.CharField(blank=True, default=None, max_length=5, null=True, verbose_name='File Type'),
        ),
    ]
