# Generated by Django 2.1.5 on 2019-02-11 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lna', '0004_auto_20190211_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exposure',
            name='file_path',
            field=models.CharField(default=None, max_length=2000, verbose_name='File Path'),
        ),
    ]
