# Generated by Django 2.1.5 on 2019-02-11 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lna', '0005_auto_20190211_1315'),
    ]

    operations = [
        migrations.AddField(
            model_name='exposure',
            name='target',
            field=models.CharField(blank=True, default=None, max_length=256, null=True, verbose_name='Target'),
        ),
    ]
