# Generated by Django 2.1.5 on 2019-02-11 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lna', '0006_exposure_target'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='exposure',
            index=models.Index(fields=['filename'], name='lna_exposur_filenam_1f8e84_idx'),
        ),
        migrations.AddIndex(
            model_name='exposure',
            index=models.Index(fields=['date'], name='lna_exposur_date_2a310b_idx'),
        ),
        migrations.AddIndex(
            model_name='exposure',
            index=models.Index(fields=['date_obs'], name='lna_exposur_date_ob_b3f2c1_idx'),
        ),
        migrations.AddIndex(
            model_name='exposure',
            index=models.Index(fields=['target'], name='lna_exposur_target_4d256e_idx'),
        ),
        migrations.AddIndex(
            model_name='exposure',
            index=models.Index(fields=['ra', 'dec'], name='lna_exposur_ra_4a1ba3_idx'),
        ),
    ]
