# Generated by Django 2.1.5 on 2019-02-11 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lna', '0007_auto_20190211_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exposure',
            name='date_obs',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Date Observation'),
        ),
    ]
