# Generated by Django 2.1.5 on 2019-02-19 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lna', '0010_auto_20190212_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='header',
            name='value',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Value'),
        ),
    ]
