# Generated by Django 2.1.5 on 2019-02-19 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lna', '0011_auto_20190219_1308'),
    ]

    operations = [
        migrations.RenameField(
            model_name='header',
            old_name='archive',
            new_name='exposure',
        ),
        migrations.AddIndex(
            model_name='header',
            index=models.Index(fields=['exposure'], name='lna_header_exposur_0dc3a1_idx'),
        ),
        migrations.AddIndex(
            model_name='header',
            index=models.Index(fields=['name'], name='lna_header_name_5122a6_idx'),
        ),
    ]
