# Generated by Django 2.2.1 on 2019-10-10 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lna', '0012_auto_20190219_1320'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='exposure',
            name='lna_exposur_date_2a310b_idx',
        ),
        migrations.RemoveField(
            model_name='exposure',
            name='date',
        ),
    ]
