# Generated by Django 2.2.1 on 2019-10-11 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lna', '0013_auto_20191010_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exposure',
            name='band',
            field=models.CharField(blank=True, default=None, max_length=24, null=True, verbose_name='Band'),
        ),
        migrations.AlterField(
            model_name='exposure',
            name='dec',
            field=models.CharField(blank=True, default=None, max_length=24, null=True, verbose_name='Dec'),
        ),
        migrations.AlterField(
            model_name='exposure',
            name='file_type',
            field=models.CharField(blank=True, default=None, max_length=8, null=True, verbose_name='File Type'),
        ),
        migrations.AlterField(
            model_name='exposure',
            name='ra',
            field=models.CharField(blank=True, default=None, max_length=24, null=True, verbose_name='RA'),
        ),
    ]
