# Generated by Django 2.1.1 on 2018-09-28 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='header',
            name='path',
            field=models.CharField(blank=True, help_text='Path', max_length=1024, null=True, verbose_name='Path'),
        ),
        migrations.AddField(
            model_name='header',
            name='simple',
            field=models.BooleanField(default=False, verbose_name='Filename'),
        ),
    ]
