# Generated by Django 2.1.1 on 2018-10-15 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fits', '0002_auto_20181015_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='header',
            name='acqmode',
            field=models.CharField(blank=True, help_text='Acquisition Mode', max_length=256, null=True, verbose_name='AcqMode'),
        ),
        migrations.AlterField(
            model_name='header',
            name='airmass',
            field=models.CharField(blank=True, help_text='Air Mass', max_length=256, null=True, verbose_name='AirMass'),
        ),
        migrations.AlterField(
            model_name='header',
            name='band',
            field=models.CharField(blank=True, help_text='Filter', max_length=256, null=True, verbose_name='Filter'),
        ),
        migrations.AlterField(
            model_name='header',
            name='calib',
            field=models.CharField(blank=True, help_text='Calibration', max_length=256, null=True, verbose_name='Calib'),
        ),
        migrations.AlterField(
            model_name='header',
            name='camgain',
            field=models.CharField(blank=True, help_text='Pre Amplifier Gain', max_length=256, null=True, verbose_name='CamGain'),
        ),
        migrations.AlterField(
            model_name='header',
            name='comment',
            field=models.CharField(blank=True, help_text='Comentario', max_length=256, null=True, verbose_name='Comment'),
        ),
        migrations.AlterField(
            model_name='header',
            name='date',
            field=models.CharField(blank=True, help_text='Date', max_length=256, null=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='header',
            name='dateobs',
            field=models.DateTimeField(blank=True, help_text='Start of Frame Exposure', max_length=256, null=True, verbose_name='Date-Obs'),
        ),
        migrations.AlterField(
            model_name='header',
            name='dec',
            field=models.CharField(blank=True, help_text='Delta', max_length=20, null=True, verbose_name='Dec'),
        ),
        migrations.AlterField(
            model_name='header',
            name='detector',
            field=models.CharField(blank=True, help_text='Head Model', max_length=256, null=True, verbose_name='Detector'),
        ),
        migrations.AlterField(
            model_name='header',
            name='dllver',
            field=models.CharField(blank=True, help_text='Software Version', max_length=256, null=True, verbose_name='DllVer'),
        ),
        migrations.AlterField(
            model_name='header',
            name='dtnwlgth',
            field=models.FloatField(blank=True, help_text='Detection Wavelength', null=True, verbose_name='Dtnwlgth'),
        ),
        migrations.AlterField(
            model_name='header',
            name='epoch',
            field=models.CharField(blank=True, help_text='Epoch', max_length=256, null=True, verbose_name='Epoch'),
        ),
        migrations.AlterField(
            model_name='header',
            name='exposure',
            field=models.CharField(blank=True, help_text='Total Exposure Time', max_length=256, null=True, verbose_name='Exposure'),
        ),
        migrations.AlterField(
            model_name='header',
            name='exptime',
            field=models.CharField(blank=True, help_text='Total Exposure Time', max_length=256, null=True, verbose_name='Exptime'),
        ),
        migrations.AlterField(
            model_name='header',
            name='extend',
            field=models.BooleanField(blank=True, default=False, help_text='Extend', null=True, verbose_name='Extend'),
        ),
        migrations.AlterField(
            model_name='header',
            name='focusval',
            field=models.CharField(blank=True, help_text='Foco Value', max_length=256, null=True, verbose_name='FocusVal'),
        ),
        migrations.AlterField(
            model_name='header',
            name='frame',
            field=models.CharField(blank=True, help_text='Start of Frame Exposure', max_length=256, null=True, verbose_name='Frame'),
        ),
        migrations.AlterField(
            model_name='header',
            name='gain',
            field=models.CharField(blank=True, help_text='Gain', max_length=256, null=True, verbose_name='Gain'),
        ),
        migrations.AlterField(
            model_name='header',
            name='ha',
            field=models.CharField(blank=True, help_text='Time Angle', max_length=256, null=True, verbose_name='Ha'),
        ),
        migrations.AlterField(
            model_name='header',
            name='hbin',
            field=models.CharField(blank=True, help_text='Horizontal Binning', max_length=256, null=True, verbose_name='Hbin'),
        ),
        migrations.AlterField(
            model_name='header',
            name='image',
            field=models.CharField(blank=True, help_text='File name', max_length=256, null=True, verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='header',
            name='imgrect',
            field=models.CharField(blank=True, help_text='Image Format', max_length=256, null=True, verbose_name='ImgRect'),
        ),
        migrations.AlterField(
            model_name='header',
            name='instrume',
            field=models.CharField(blank=True, help_text='Start of Frame Exposure', max_length=256, null=True, verbose_name='Instrument'),
        ),
        migrations.AlterField(
            model_name='header',
            name='jd',
            field=models.CharField(blank=True, help_text='Juliana Date', max_length=256, null=True, verbose_name='Jd'),
        ),
        migrations.AlterField(
            model_name='header',
            name='naxis',
            field=models.PositiveIntegerField(blank=True, default=False, help_text='Naxis', null=True, verbose_name='Naxis'),
        ),
        migrations.AlterField(
            model_name='header',
            name='naxis1',
            field=models.PositiveIntegerField(blank=True, default=False, help_text='BitPix', null=True, verbose_name='Naxis1'),
        ),
        migrations.AlterField(
            model_name='header',
            name='naxis2',
            field=models.PositiveIntegerField(blank=True, default=False, help_text='Naxis2', null=True, verbose_name='Naxis2'),
        ),
        migrations.AlterField(
            model_name='header',
            name='observer',
            field=models.CharField(blank=True, help_text='Observer', max_length=256, null=True, verbose_name='Observer'),
        ),
        migrations.AlterField(
            model_name='header',
            name='operatn',
            field=models.PositiveIntegerField(blank=True, help_text='Type of System', null=True, verbose_name='OperaTn'),
        ),
        migrations.AlterField(
            model_name='header',
            name='outptamp',
            field=models.CharField(blank=True, help_text='Output Amplifier', max_length=256, null=True, verbose_name='OutptAmp'),
        ),
        migrations.AlterField(
            model_name='header',
            name='platescl',
            field=models.CharField(blank=True, help_text='Plate Scale', max_length=256, null=True, verbose_name='Platescl'),
        ),
        migrations.AlterField(
            model_name='header',
            name='preamp',
            field=models.CharField(blank=True, help_text='Pre Amplifier Gain', max_length=256, null=True, verbose_name='PreAmp'),
        ),
        migrations.AlterField(
            model_name='header',
            name='ra',
            field=models.CharField(blank=True, help_text='Alpha', max_length=20, null=True, verbose_name='Ra'),
        ),
        migrations.AlterField(
            model_name='header',
            name='rdnoise',
            field=models.CharField(blank=True, help_text='Reading Noise', max_length=256, null=True, verbose_name='RdNoise'),
        ),
        migrations.AlterField(
            model_name='header',
            name='readmode',
            field=models.CharField(blank=True, help_text='Readout Mode', max_length=256, null=True, verbose_name='ReadMode'),
        ),
        migrations.AlterField(
            model_name='header',
            name='readtime',
            field=models.FloatField(blank=True, help_text='Pixel readout time', null=True, verbose_name='ReadTime'),
        ),
        migrations.AlterField(
            model_name='header',
            name='serno',
            field=models.CharField(blank=True, help_text='Serial Number', max_length=256, null=True, verbose_name='Serno'),
        ),
        migrations.AlterField(
            model_name='header',
            name='sntvty',
            field=models.FloatField(blank=True, help_text='Sensitivity', null=True, verbose_name='Sntvty'),
        ),
        migrations.AlterField(
            model_name='header',
            name='st',
            field=models.CharField(blank=True, help_text='Sidereal Time', max_length=256, null=True, verbose_name='St'),
        ),
        migrations.AlterField(
            model_name='header',
            name='subrect',
            field=models.CharField(blank=True, help_text='Sub Image Format', max_length=256, null=True, verbose_name='SubRect'),
        ),
        migrations.AlterField(
            model_name='header',
            name='telescop',
            field=models.CharField(blank=True, help_text='Telescop', max_length=256, null=True, verbose_name='Telescop'),
        ),
        migrations.AlterField(
            model_name='header',
            name='temp',
            field=models.CharField(blank=True, help_text='Temperature', max_length=256, null=True, verbose_name='Temp'),
        ),
        migrations.AlterField(
            model_name='header',
            name='trigger',
            field=models.CharField(blank=True, help_text='Trigger Mode', max_length=256, null=True, verbose_name='Trigger'),
        ),
        migrations.AlterField(
            model_name='header',
            name='unsttemp',
            field=models.CharField(blank=True, help_text='Unstabilized Temperature', max_length=256, null=True, verbose_name='UnstTemp'),
        ),
        migrations.AlterField(
            model_name='header',
            name='vbin',
            field=models.CharField(blank=True, help_text='Vertical Binning', max_length=256, null=True, verbose_name='Vbin'),
        ),
        migrations.AlterField(
            model_name='header',
            name='vshift',
            field=models.CharField(blank=True, help_text='Vertical Shift Speed', max_length=256, null=True, verbose_name='VShift'),
        ),
        migrations.AlterField(
            model_name='header',
            name='wbar',
            field=models.FloatField(blank=True, help_text='Atmospheric Pressure', null=True, verbose_name='W-Bar'),
        ),
        migrations.AlterField(
            model_name='header',
            name='whum',
            field=models.CharField(blank=True, help_text='Moisture', max_length=256, null=True, verbose_name='W-Hum'),
        ),
        migrations.AlterField(
            model_name='header',
            name='wtemp',
            field=models.FloatField(blank=True, help_text='Ambiente Temperature', null=True, verbose_name='W-Temp'),
        ),
        migrations.AlterField(
            model_name='header',
            name='xtype',
            field=models.CharField(blank=True, help_text='Calibration Type', max_length=256, null=True, verbose_name='XType'),
        ),
    ]
