# Generated by Django 2.1.1 on 2018-10-15 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fits', '0003_auto_20181015_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='header',
            name='extend',
            field=models.BooleanField(default=False, help_text='Extend', null=True, verbose_name='Extend'),
        ),
    ]
