# Generated by Django 2.1.1 on 2018-10-15 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fits', '0004_auto_20181015_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='header',
            name='extend',
            field=models.BooleanField(default=False, help_text='Extend', verbose_name='Extend'),
        ),
    ]
