# Generated by Django 2.1.1 on 2018-10-15 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fits', '0005_auto_20181015_2004'),
    ]

    operations = [
        migrations.AddField(
            model_name='header',
            name='archive',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='fits.Exposure'),
            preserve_default=False,
        ),
    ]
