version: '3'

services:
  # Database Postgres + Q3C
  database:
    image: linea/postgresql_q3c:latest
    restart: always
    env_file:
      - .env
    expose:
      - 5432
    volumes:
      - ./pg_data:/var/lib/postgresql/data
      - ./pg_backups:/pg_backups
      - ./initial_data:/data

  #Backend Django
  backend:
    build: ./backend
    image: fits_manage_backend
    # user: 1000:1000
    env_file:
      - .env    
    volumes:
      - ./backend:/app
      - ./log:/log
      - ./archive:/archive      
    ports:
      - 8081:8081
    depends_on:
      - database


  # Servidor Web NGINX
  nginx:
    build: ./frontend
     # image: linea/lna:FRONT4dcb1d66cd5f190e9846856ff3e5c112ac207b05
    ports:
      - 80:8080
    volumes:
      #./development.conf:/etc/nginx/conf.d/default.conf:ro
      - ./imagens:/var/www/data
      - ./frontend/nginx-proxy-develop.conf:/nginx/conf.d/default.conf
      - ./frontend:/nginx/conf.d/default.conf
    cap_drop:
      - ALL
    depends_on:
      - backend
