version: '3'

services:
  # Database Postgres + Q3C
  database:
    image: linea/postgresql_q3c:latest
    restart: always
    env_file:
      - .env
    expose:
      - 5432
    volumes:
      - ./pg_data:/var/lib/postgresql/data
      - ./pg_backups:/pg_backups
      - ./initial_data:/data

  #Backend Django
  backend:
    build: ./backend
    image: fits_manage_backend
    user: 1000:1000
    env_file:
      - .env    
    volumes:
      - ./backend:/app
      - ./log:/log
      - ./archive:/archive      
    ports:
      - 8081:8081
    depends_on:
      - database


  # Servidor Web NGINX
  nginx:
    build: ./nginx
    ports:
      - 80:8080
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    cap_drop:
      - ALL
    depends_on:
      - backend